# Generated by Django 3.1 on 2021-04-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('slug', models.SlugField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, default='account/default.jpg', null=True, upload_to='genres')),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=150)),
                ('producer', models.CharField(max_length=100)),
                ('image', models.ImageField(default='account/default.jpg', upload_to='films')),
                ('video', models.FileField(upload_to='video')),
                ('genre', models.ManyToManyField(to='main.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author: ')),
                ('comment_text', models.CharField(max_length=500, verbose_name='Comment: ')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.films')),
            ],
        ),
    ]
